actor:
  alg: dqn
  env: CartPole-v1
  num_steps: 5000
  data_port: 5000
  param_port: 5001
  num_replicas: 4
  model: qmlp
  max_steps_per_update: 1
  num_saved_ckpt: 10
  max_episode_length: 1000

agent:
  gamma: 0.99
  lr: 0.001
  epochs: 1
  epsilon: 1
  epsilon_min: 0.01
  exploration_fraction: 0.5
  update_freq: 1000
  training_start: 5000
  model:
    - model_id: policy_model
    - model_id: target_model
