learner:
  alg: ppo
  env: QbertNoFrameskip-v4
  num_steps: 10000000
  data_port: 5002
  param_port: 5003
  model: accnn
  pool_size: 1280
  training_freq: 1
  batch_size: 1280

agent:
  gamma: 0.99
  lam: 0.95
  lr: 0.00025
  clip_range: 0.1
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  epochs: 4
  nminibatches: 4
  model:
    model_id: policy_model
