learner:
  alg: dqn
  env: CartPole-v1
  num_steps: 20000
  data_port: 5000
  param_port: 5001
  model: qmlp
  pool_size: 5000
  training_freq: 1
  batch_size: 32

agent:
  gamma: 0.99
  lr: 0.0005
  epochs: 1
  epsilon: 1
  epsilon_min: 0.01
  exploration_fraction: 0.1
  update_freq: 50
  training_start: 100
  model:
    - model_id: policy_model
    - model_id: target_model
