learner:
  alg: dqn
  env: PongNoFrameskip-v4
  num_steps: 1000000
  data_port: 5000
  param_port: 5001
  model: qcnn
  pool_size: 5000
  training_freq: 1
  batch_size: 32

agent:
  gamma: 0.99
  lr: 5.0e-05
  epochs: 1
  epsilon: 1
  epsilon_min: 0.01
  exploration_fraction: 0.1
  update_freq: 1000
  training_start: 5000
  model:
    - model_id: policy_model
    - model_id: target_model
